/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CAmqpBrokerCollectionDoc_h_
#define CAmqpBrokerCollectionDoc_h_

namespace Caf {

/// A simple container for objects of type AmqpBrokerCollection
class CAmqpBrokerCollectionDoc {
public:
	CAmqpBrokerCollectionDoc() :
		_isInitialized(false) {}
	virtual ~CAmqpBrokerCollectionDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<SmartPtrCAmqpBrokerDoc> amqpBroker = std::deque<SmartPtrCAmqpBrokerDoc>()) {
		if (! _isInitialized) {
			_amqpBroker = amqpBroker;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the AmqpBroker
	std::deque<SmartPtrCAmqpBrokerDoc> getAmqpBroker() const {
		return _amqpBroker;
	}

private:
	bool _isInitialized;

	std::deque<SmartPtrCAmqpBrokerDoc> _amqpBroker;

private:
	CAF_CM_DECLARE_NOCOPY(CAmqpBrokerCollectionDoc);
};

CAF_DECLARE_SMART_POINTER(CAmqpBrokerCollectionDoc);

}

#endif
