/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CRemoteSecurityCollectionDoc_h_
#define CRemoteSecurityCollectionDoc_h_

namespace Caf {

/// A simple container for objects of type RemoteSecurityCollection
class CRemoteSecurityCollectionDoc {
public:
	CRemoteSecurityCollectionDoc() :
		_isInitialized(false) {}
	virtual ~CRemoteSecurityCollectionDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<SmartPtrCRemoteSecurityDoc> remoteSecurity = std::deque<SmartPtrCRemoteSecurityDoc>()) {
		if (! _isInitialized) {
			_remoteSecurity = remoteSecurity;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the RemoteSecurity
	std::deque<SmartPtrCRemoteSecurityDoc> getRemoteSecurity() const {
		return _remoteSecurity;
	}

private:
	bool _isInitialized;

	std::deque<SmartPtrCRemoteSecurityDoc> _remoteSecurity;

private:
	CAF_CM_DECLARE_NOCOPY(CRemoteSecurityCollectionDoc);
};

CAF_DECLARE_SMART_POINTER(CRemoteSecurityCollectionDoc);

}

#endif
