/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ProviderCollectInstancesXml_h_
#define ProviderCollectInstancesXml_h_


#include "Doc/ProviderRequestDoc/CProviderCollectInstancesDoc.h"

#include "Doc/DocXml/ProviderRequestXml/ProviderRequestXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the ProviderCollectInstances class to/from XML
	namespace ProviderCollectInstancesXml {

		/// Adds the ProviderCollectInstancesDoc into the XML.
		void PROVIDERREQUESTXML_LINKAGE add(
			const SmartPtrCProviderCollectInstancesDoc providerCollectInstancesDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ProviderCollectInstancesDoc from the XML.
		SmartPtrCProviderCollectInstancesDoc PROVIDERREQUESTXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
