/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ProviderInvokeOperationXml_h_
#define ProviderInvokeOperationXml_h_


#include "Doc/ProviderRequestDoc/CProviderInvokeOperationDoc.h"

#include "Doc/DocXml/ProviderRequestXml/ProviderRequestXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the ProviderInvokeOperation class to/from XML
	namespace ProviderInvokeOperationXml {

		/// Adds the ProviderInvokeOperationDoc into the XML.
		void PROVIDERREQUESTXML_LINKAGE add(
			const SmartPtrCProviderInvokeOperationDoc providerInvokeOperationDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ProviderInvokeOperationDoc from the XML.
		SmartPtrCProviderInvokeOperationDoc PROVIDERREQUESTXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
