/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ProviderInvokeOperationCollectionXml_h_
#define ProviderInvokeOperationCollectionXml_h_


#include "Doc/ProviderRequestDoc/CProviderInvokeOperationCollectionDoc.h"

#include "Doc/DocXml/ProviderRequestXml/ProviderRequestXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the ProviderInvokeOperationCollection class to/from XML
	namespace ProviderInvokeOperationCollectionXml {

		/// Adds the ProviderInvokeOperationCollectionDoc into the XML.
		void PROVIDERREQUESTXML_LINKAGE add(
			const SmartPtrCProviderInvokeOperationCollectionDoc providerInvokeOperationCollectionDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ProviderInvokeOperationCollectionDoc from the XML.
		SmartPtrCProviderInvokeOperationCollectionDoc PROVIDERREQUESTXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
