/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ProviderRequestHeaderXml_h_
#define ProviderRequestHeaderXml_h_


#include "Doc/ProviderRequestDoc/CProviderRequestHeaderDoc.h"

#include "Doc/DocXml/ProviderRequestXml/ProviderRequestXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the ProviderRequestHeader class to/from XML
	namespace ProviderRequestHeaderXml {

		/// Adds the ProviderRequestHeaderDoc into the XML.
		void PROVIDERREQUESTXML_LINKAGE add(
			const SmartPtrCProviderRequestHeaderDoc providerRequestHeaderDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ProviderRequestHeaderDoc from the XML.
		SmartPtrCProviderRequestHeaderDoc PROVIDERREQUESTXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
