/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef MgmtCollectInstancesCollectionXml_h_
#define MgmtCollectInstancesCollectionXml_h_


#include "Doc/MgmtTypesDoc/CMgmtCollectInstancesCollectionDoc.h"

#include "Doc/DocXml/MgmtTypesXml/MgmtTypesXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the MgmtCollectInstancesCollection class to/from XML
	namespace MgmtCollectInstancesCollectionXml {

		/// Adds the MgmtCollectInstancesCollectionDoc into the XML.
		void MGMTTYPESXML_LINKAGE add(
			const SmartPtrCMgmtCollectInstancesCollectionDoc mgmtCollectInstancesCollectionDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the MgmtCollectInstancesCollectionDoc from the XML.
		SmartPtrCMgmtCollectInstancesCollectionDoc MGMTTYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
