/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef MultiPmeMgmtBatchXml_h_
#define MultiPmeMgmtBatchXml_h_


#include "Doc/MultiPmeMgmtRequestDoc/CMultiPmeMgmtBatchDoc.h"

#include "Doc/DocXml/MultiPmeMgmtRequestXml/MultiPmeMgmtRequestXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the MultiPmeMgmtBatch class to/from XML
	namespace MultiPmeMgmtBatchXml {

		/// Adds the MultiPmeMgmtBatchDoc into the XML.
		void MULTIPMEMGMTREQUESTXML_LINKAGE add(
			const SmartPtrCMultiPmeMgmtBatchDoc multiPmeMgmtBatchDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the MultiPmeMgmtBatchDoc from the XML.
		SmartPtrCMultiPmeMgmtBatchDoc MULTIPMEMGMTREQUESTXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
