/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef MultiPmeMgmtRequestXml_h_
#define MultiPmeMgmtRequestXml_h_


#include "Doc/MultiPmeMgmtRequestDoc/CMultiPmeMgmtRequestDoc.h"

#include "Doc/DocXml/MultiPmeMgmtRequestXml/MultiPmeMgmtRequestXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the MultiPmeMgmtRequest class to/from XML
	namespace MultiPmeMgmtRequestXml {

		/// Adds the MultiPmeMgmtRequestDoc into the XML.
		void MULTIPMEMGMTREQUESTXML_LINKAGE add(
			const SmartPtrCMultiPmeMgmtRequestDoc multiPmeMgmtRequestDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the MultiPmeMgmtRequestDoc from the XML.
		SmartPtrCMultiPmeMgmtRequestDoc MULTIPMEMGMTREQUESTXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
