/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CDefinitionObjectCollectionDoc_h_
#define CDefinitionObjectCollectionDoc_h_

namespace Caf {

/// Set of elements containing data returned as a result of a provider collection or action
class CDefinitionObjectCollectionDoc {
public:
	CDefinitionObjectCollectionDoc() :
		_isInitialized(false) {}
	virtual ~CDefinitionObjectCollectionDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<std::string> value) {
		if (! _isInitialized) {
			_value = value;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the Value
	std::deque<std::string> getValue() const {
		return _value;
	}

private:
	bool _isInitialized;

	std::deque<std::string> _value;

private:
	CAF_CM_DECLARE_NOCOPY(CDefinitionObjectCollectionDoc);
};

CAF_DECLARE_SMART_POINTER(CDefinitionObjectCollectionDoc);

}

#endif
