/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ActionClassXml_h_
#define ActionClassXml_h_

namespace Caf {

	/// Streams the ActionClass class to/from XML
	namespace ActionClassXml {

		/// Adds the ActionClassDoc into the XML.
		void SCHEMATYPESXML_LINKAGE add(
			const SmartPtrCActionClassDoc actionClassDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ActionClassDoc from the XML.
		SmartPtrCActionClassDoc SCHEMATYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
