/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ClassPropertyXml_h_
#define ClassPropertyXml_h_

namespace Caf {

	/// Streams the ClassProperty class to/from XML
	namespace ClassPropertyXml {

		/// Adds the ClassPropertyDoc into the XML.
		void SCHEMATYPESXML_LINKAGE add(
			const SmartPtrCClassPropertyDoc classPropertyDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ClassPropertyDoc from the XML.
		SmartPtrCClassPropertyDoc SCHEMATYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
