/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef InstanceOperationCollectionXml_h_
#define InstanceOperationCollectionXml_h_

namespace Caf {

	/// Streams the InstanceOperationCollection class to/from XML
	namespace InstanceOperationCollectionXml {

		/// Adds the InstanceOperationCollectionDoc into the XML.
		void SCHEMATYPESXML_LINKAGE add(
			const SmartPtrCInstanceOperationCollectionDoc instanceOperationCollectionDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the InstanceOperationCollectionDoc from the XML.
		SmartPtrCInstanceOperationCollectionDoc SCHEMATYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
