/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef SchemaTypesXml_Inc_h_
#define SchemaTypesXml_Inc_h_

#include "../CafCoreTypesXml/CafCoreTypesXmlLink.h"
#include "ClassPropertyXml.h"
#include "ClassInstancePropertyXml.h"
#include "MethodParameterXml.h"
#include "InstanceParameterXml.h"
#include "ClassIdentifierXml.h"
#include "MethodXml.h"
#include "CollectMethodXml.h"
#include "ClassCardinalityXml.h"
#include "ClassFieldXml.h"
#include "RelationshipXml.h"
#include "PhysicalRelationshipXml.h"
#include "JoinTypeXml.h"
#include "LogicalRelationshipXml.h"
#include "DataClassXml.h"
#include "CmdlMetadataXml.h"
#include "CmdlUnionXml.h"
#include "DataClassPropertyXml.h"
#include "DataClassSubInstanceXml.h"
#include "DataClassInstanceXml.h"
#include "DataClassInstanceCollectionXml.h"
#include "InstanceOperationXml.h"
#include "InstanceOperationCollectionXml.h"
#include "ActionClassInstanceXml.h"
#include "ActionClassInstanceCollectionXml.h"
#include "ActionClassXml.h"

#endif /* SchemaTypesXml_Inc_h_ */
