/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef SchemaXml_h_
#define SchemaXml_h_


#include "Doc/ProviderResultsDoc/CSchemaDoc.h"

#include "Doc/DocXml/ProviderResultsXml/ProviderResultsXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the Schema class to/from XML
	namespace SchemaXml {

		/// Adds the SchemaDoc into the XML.
		void PROVIDERRESULTSXML_LINKAGE add(
			const SmartPtrCSchemaDoc schemaDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the SchemaDoc from the XML.
		SmartPtrCSchemaDoc PROVIDERRESULTSXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
