/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ClassCollectionXml_h_
#define ClassCollectionXml_h_


#include "Doc/ProviderInfraDoc/CClassCollectionDoc.h"

#include "Doc/DocXml/ProviderInfraXml/ProviderInfraXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the ClassCollection class to/from XML
	namespace ClassCollectionXml {

		/// Adds the ClassCollectionDoc into the XML.
		void PROVIDERINFRAXML_LINKAGE add(
			const SmartPtrCClassCollectionDoc classCollectionDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ClassCollectionDoc from the XML.
		SmartPtrCClassCollectionDoc PROVIDERINFRAXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
