/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ProviderRegXml_h_
#define ProviderRegXml_h_


#include "Doc/ProviderInfraDoc/CProviderRegDoc.h"

#include "Doc/DocXml/ProviderInfraXml/ProviderInfraXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the ProviderReg class to/from XML
	namespace ProviderRegXml {

		/// Adds the ProviderRegDoc into the XML.
		void PROVIDERINFRAXML_LINKAGE add(
			const SmartPtrCProviderRegDoc providerRegDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ProviderRegDoc from the XML.
		SmartPtrCProviderRegDoc PROVIDERINFRAXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
