/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef AddInCollectionXml_h_
#define AddInCollectionXml_h_

namespace Caf {

	/// Streams the AddInCollection class to/from XML
	namespace AddInCollectionXml {

		/// Adds the AddInCollectionDoc into the XML.
		void CAFCORETYPESXML_LINKAGE add(
			const SmartPtrCAddInCollectionDoc addInCollectionDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the AddInCollectionDoc from the XML.
		SmartPtrCAddInCollectionDoc CAFCORETYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
