/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef PropertyCollectionXml_h_
#define PropertyCollectionXml_h_

namespace Caf {

	/// Streams the PropertyCollection class to/from XML
	namespace PropertyCollectionXml {

		/// Adds the PropertyCollectionDoc into the XML.
		void CAFCORETYPESXML_LINKAGE add(
			const SmartPtrCPropertyCollectionDoc propertyCollectionDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the PropertyCollectionDoc from the XML.
		SmartPtrCPropertyCollectionDoc CAFCORETYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
