/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CCertCollectionDoc_h_
#define CCertCollectionDoc_h_

namespace Caf {

/// A simple container for objects of type CertCollection
class CCertCollectionDoc {
public:
	CCertCollectionDoc() :
		_isInitialized(false) {}
	virtual ~CCertCollectionDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<std::string> certCollection = std::deque<std::string>()) {
		if (! _isInitialized) {
			_certCollection = certCollection;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the Cert
	std::deque<std::string> getCert() const {
		return _certCollection;
	}

private:
	bool _isInitialized;

	std::deque<std::string> _certCollection;

private:
	CAF_CM_DECLARE_NOCOPY(CCertCollectionDoc);
};

CAF_DECLARE_SMART_POINTER(CCertCollectionDoc);

}

#endif
