/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CEventManifestDoc_h_
#define CEventManifestDoc_h_

namespace Caf {

/// A simple container for objects of type EventManifest
class CEventManifestDoc {
public:
	CEventManifestDoc() :
		_isInitialized(false) {}
	virtual ~CEventManifestDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::string classNamespace,
		const std::string className,
		const std::string classVersion,
		const std::string operationName,
		const SmartPtrCAttachmentCollectionDoc attachmentCollection) {
		if (! _isInitialized) {
			_classNamespace = classNamespace;
			_className = className;
			_classVersion = classVersion;
			_operationName = operationName;
			_attachmentCollection = attachmentCollection;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the ClassNamespace
	std::string getClassNamespace() const {
		return _classNamespace;
	}

	/// Accessor for the ClassName
	std::string getClassName() const {
		return _className;
	}

	/// Accessor for the ClassVersion
	std::string getClassVersion() const {
		return _classVersion;
	}

	/// Accessor for the OperationName
	std::string getOperationName() const {
		return _operationName;
	}

	/// Accessor for the AttachmentCollection
	SmartPtrCAttachmentCollectionDoc getAttachmentCollection() const {
		return _attachmentCollection;
	}

private:
	bool _isInitialized;

	std::string _classNamespace;
	std::string _className;
	std::string _classVersion;
	std::string _operationName;
	SmartPtrCAttachmentCollectionDoc _attachmentCollection;

private:
	CAF_CM_DECLARE_NOCOPY(CEventManifestDoc);
};

CAF_DECLARE_SMART_POINTER(CEventManifestDoc);

}

#endif
