/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CProviderEventResponseDoc_h_
#define CProviderEventResponseDoc_h_

namespace Caf {

/// A simple container for objects of type ProviderEventResponse
class CProviderEventResponseDoc {
public:
	CProviderEventResponseDoc() :
		_isInitialized(false) {}
	virtual ~CProviderEventResponseDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::string pmeId,
		const SmartPtrCResponseHeaderDoc responseHeader,
		const SmartPtrCEventManifestDoc manifest,
		const SmartPtrCEventKeyCollectionDoc eventKeyCollection,
		const SmartPtrCStatisticsDoc statistics) {
		if (! _isInitialized) {
			_pmeId = pmeId;
			_responseHeader = responseHeader;
			_manifest = manifest;
			_eventKeyCollection = eventKeyCollection;
			_statistics = statistics;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the PmeId
	std::string getPmeId() const {
		return _pmeId;
	}

	/// Accessor for the ResponseHeader
	SmartPtrCResponseHeaderDoc getResponseHeader() const {
		return _responseHeader;
	}

	/// Accessor for the Manifest
	SmartPtrCEventManifestDoc getManifest() const {
		return _manifest;
	}

	/// Accessor for the EventKeyCollection
	SmartPtrCEventKeyCollectionDoc getEventKeyCollection() const {
		return _eventKeyCollection;
	}

	/// Accessor for the Statistics
	SmartPtrCStatisticsDoc getStatistics() const {
		return _statistics;
	}

private:
	bool _isInitialized;

	std::string _pmeId;
	SmartPtrCResponseHeaderDoc _responseHeader;
	SmartPtrCEventManifestDoc _manifest;
	SmartPtrCEventKeyCollectionDoc _eventKeyCollection;
	SmartPtrCStatisticsDoc _statistics;

private:
	CAF_CM_DECLARE_NOCOPY(CProviderEventResponseDoc);
};

CAF_DECLARE_SMART_POINTER(CProviderEventResponseDoc);

}

#endif
