/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CAttachmentCollectionDoc_h_
#define CAttachmentCollectionDoc_h_

namespace Caf {

/// A simple container for objects of type AttachmentCollection
class CAttachmentCollectionDoc {
public:
	CAttachmentCollectionDoc() :
		_isInitialized(false) {}
	virtual ~CAttachmentCollectionDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<SmartPtrCAttachmentDoc> attachment = std::deque<SmartPtrCAttachmentDoc>(),
		const std::deque<SmartPtrCInlineAttachmentDoc> inlineAttachment = std::deque<SmartPtrCInlineAttachmentDoc>()) {
		if (! _isInitialized) {
			_attachment = attachment;
			_inlineAttachment = inlineAttachment;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the Attachment
	std::deque<SmartPtrCAttachmentDoc> getAttachment() const {
		return _attachment;
	}

	/// Accessor for the InlineAttachment
	std::deque<SmartPtrCInlineAttachmentDoc> getInlineAttachment() const {
		return _inlineAttachment;
	}

private:
	bool _isInitialized;

	std::deque<SmartPtrCAttachmentDoc> _attachment;
	std::deque<SmartPtrCInlineAttachmentDoc> _inlineAttachment;

private:
	CAF_CM_DECLARE_NOCOPY(CAttachmentCollectionDoc);
};

CAF_DECLARE_SMART_POINTER(CAttachmentCollectionDoc);

}

#endif
