/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CClassSpecifierDoc_h_
#define CClassSpecifierDoc_h_

namespace Caf {

/// A simple container for objects of type ClassSpecifier
class CClassSpecifierDoc {
public:
	CClassSpecifierDoc() :
		_isInitialized(false) {}
	virtual ~CClassSpecifierDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const SmartPtrCFullyQualifiedClassGroupDoc fullyQualifiedClass = SmartPtrCFullyQualifiedClassGroupDoc(),
		const SmartPtrCClassFiltersDoc classFilters = SmartPtrCClassFiltersDoc()) {
		if (! _isInitialized) {
			_fullyQualifiedClass = fullyQualifiedClass;
			_classFilters = classFilters;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the FullyQualifiedClass
	SmartPtrCFullyQualifiedClassGroupDoc getFullyQualifiedClass() const {
		return _fullyQualifiedClass;
	}

	/// Accessor for the ClassFilters
	SmartPtrCClassFiltersDoc getClassFilters() const {
		return _classFilters;
	}

private:
	bool _isInitialized;

	SmartPtrCFullyQualifiedClassGroupDoc _fullyQualifiedClass;
	SmartPtrCClassFiltersDoc _classFilters;

private:
	CAF_CM_DECLARE_NOCOPY(CClassSpecifierDoc);
};

CAF_DECLARE_SMART_POINTER(CClassSpecifierDoc);

}

#endif
