/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CPropertyCollectionDoc_h_
#define CPropertyCollectionDoc_h_

namespace Caf {

/// A simple container for objects of type PropertyCollection
class CPropertyCollectionDoc {
public:
	CPropertyCollectionDoc() :
		_isInitialized(false) {}
	virtual ~CPropertyCollectionDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<SmartPtrCPropertyDoc> property = std::deque<SmartPtrCPropertyDoc>()) {
		if (! _isInitialized) {
			_property = property;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the Property
	std::deque<SmartPtrCPropertyDoc> getProperty() const {
		return _property;
	}

private:
	bool _isInitialized;

	std::deque<SmartPtrCPropertyDoc> _property;

private:
	CAF_CM_DECLARE_NOCOPY(CPropertyCollectionDoc);
};

CAF_DECLARE_SMART_POINTER(CPropertyCollectionDoc);

}

#endif
