/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CClassCollectionDoc_h_
#define CClassCollectionDoc_h_

namespace Caf {

/// A simple container for objects of type ClassCollection
class CClassCollectionDoc {
public:
	CClassCollectionDoc() :
		_isInitialized(false) {}
	virtual ~CClassCollectionDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<SmartPtrCFullyQualifiedClassGroupDoc> fullyQualifiedClass) {
		if (! _isInitialized) {
			_fullyQualifiedClass = fullyQualifiedClass;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the FullyQualifiedClass
	std::deque<SmartPtrCFullyQualifiedClassGroupDoc> getFullyQualifiedClass() const {
		return _fullyQualifiedClass;
	}

private:
	bool _isInitialized;

	std::deque<SmartPtrCFullyQualifiedClassGroupDoc> _fullyQualifiedClass;

private:
	CAF_CM_DECLARE_NOCOPY(CClassCollectionDoc);
};

CAF_DECLARE_SMART_POINTER(CClassCollectionDoc);

}

#endif
