/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef DiagDeleteValueCollectionXml_h_
#define DiagDeleteValueCollectionXml_h_


#include "Doc/DiagTypesDoc/CDiagDeleteValueCollectionDoc.h"

#include "Doc/DocXml/DiagTypesXml/DiagTypesXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the DiagDeleteValueCollection class to/from XML
	namespace DiagDeleteValueCollectionXml {

		/// Adds the DiagDeleteValueCollectionDoc into the XML.
		void DIAGTYPESXML_LINKAGE add(
			const SmartPtrCDiagDeleteValueCollectionDoc diagDeleteValueCollectionDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the DiagDeleteValueCollectionDoc from the XML.
		SmartPtrCDiagDeleteValueCollectionDoc DIAGTYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
