/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CInstanceOperationDoc_h_
#define CInstanceOperationDoc_h_

namespace Caf {

/// A simple container for objects of type InstanceOperation
class CInstanceOperationDoc {
public:
	CInstanceOperationDoc() :
		_isInitialized(false) {}
	virtual ~CInstanceOperationDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::string operationName,
		const std::string moniker) {
		if (! _isInitialized) {
			_operationName = operationName;
			_moniker = moniker;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the OperationName
	std::string getOperationName() const {
		return _operationName;
	}

	/// Accessor for the Moniker
	std::string getMoniker() const {
		return _moniker;
	}

private:
	bool _isInitialized;

	std::string _operationName;
	std::string _moniker;

private:
	CAF_CM_DECLARE_NOCOPY(CInstanceOperationDoc);
};

CAF_DECLARE_SMART_POINTER(CInstanceOperationDoc);

}

#endif
