#define BUILD_NUMBER \
	"build-100027"
#define BUILD_NUMBER_NUMERIC \
	100027
#define BUILD_NUMBER_NUMERIC_STRING \
	"100027"
#define PRODUCT_BUILD_NUMBER \
	"product-build-231"
#define PRODUCT_BUILD_NUMBER_NUMERIC \
	231
#define PRODUCT_BUILD_NUMBER_NUMERIC_STRING \
	"231"
