/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef InstallProviderJobXml_h_
#define InstallProviderJobXml_h_

namespace Caf {

	/// Streams the InstallProviderJob class to/from XML
	namespace InstallProviderJobXml {

		/// Adds the InstallProviderJobDoc into the XML.
		void CAFINSTALLREQUESTXML_LINKAGE add(
			const SmartPtrCInstallProviderJobDoc installProviderJobDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the InstallProviderJobDoc from the XML.
		SmartPtrCInstallProviderJobDoc CAFINSTALLREQUESTXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
