/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef STDAFX_H_
#define STDAFX_H_

#include <CommonDefines.h>
#include <DocContracts.h>
#include "DocUtilsLink.h"

#endif /* STDAFX_H_ */
