/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef DiagTypesXml_Inc_h_
#define DiagTypesXml_Inc_h_

#include "../CafCoreTypesXml/CafCoreTypesXmlLink.h"
#include "DiagCollectInstancesXml.h"
#include "DiagSetValueXml.h"
#include "DiagSetValueCollectionXml.h"
#include "DiagDeleteValueXml.h"
#include "DiagDeleteValueCollectionXml.h"
#include "DiagBatchXml.h"

#endif /* DiagTypesXml_Inc_h_ */
