/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef DiagBatchXml_h_
#define DiagBatchXml_h_

namespace Caf {

	/// Streams the DiagBatch class to/from XML
	namespace DiagBatchXml {

		/// Adds the DiagBatchDoc into the XML.
		void DIAGTYPESXML_LINKAGE add(
			const SmartPtrCDiagBatchDoc diagBatchDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the DiagBatchDoc from the XML.
		SmartPtrCDiagBatchDoc DIAGTYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
