/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef AuthnAuthzXml_h_
#define AuthnAuthzXml_h_


#include "Doc/CafCoreTypesDoc/CAuthnAuthzDoc.h"

#include "Doc/DocXml/CafCoreTypesXml/CafCoreTypesXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the AuthnAuthz class to/from XML
	namespace AuthnAuthzXml {

		/// Adds the AuthnAuthzDoc into the XML.
		void CAFCORETYPESXML_LINKAGE add(
			const SmartPtrCAuthnAuthzDoc authnAuthzDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the AuthnAuthzDoc from the XML.
		SmartPtrCAuthnAuthzDoc CAFCORETYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
