/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ClassFiltersXml_h_
#define ClassFiltersXml_h_


#include "Doc/CafCoreTypesDoc/CClassFiltersDoc.h"

#include "Doc/DocXml/CafCoreTypesXml/CafCoreTypesXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the ClassFilters class to/from XML
	namespace ClassFiltersXml {

		/// Adds the ClassFiltersDoc into the XML.
		void CAFCORETYPESXML_LINKAGE add(
			const SmartPtrCClassFiltersDoc classFiltersDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ClassFiltersDoc from the XML.
		SmartPtrCClassFiltersDoc CAFCORETYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
