/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef LoggingLevelCollectionXml_h_
#define LoggingLevelCollectionXml_h_


#include "Doc/CafCoreTypesDoc/CLoggingLevelCollectionDoc.h"

#include "Doc/DocXml/CafCoreTypesXml/CafCoreTypesXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the LoggingLevelCollection class to/from XML
	namespace LoggingLevelCollectionXml {

		/// Adds the LoggingLevelCollectionDoc into the XML.
		void CAFCORETYPESXML_LINKAGE add(
			const SmartPtrCLoggingLevelCollectionDoc loggingLevelCollectionDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the LoggingLevelCollectionDoc from the XML.
		SmartPtrCLoggingLevelCollectionDoc CAFCORETYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
