/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ProtocolXml_h_
#define ProtocolXml_h_


#include "Doc/CafCoreTypesDoc/CProtocolDoc.h"

#include "Doc/DocXml/CafCoreTypesXml/CafCoreTypesXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the Protocol class to/from XML
	namespace ProtocolXml {

		/// Adds the ProtocolDoc into the XML.
		void CAFCORETYPESXML_LINKAGE add(
			const SmartPtrCProtocolDoc protocolDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ProtocolDoc from the XML.
		SmartPtrCProtocolDoc CAFCORETYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
