/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ProtocolCollectionXml_h_
#define ProtocolCollectionXml_h_


#include "Doc/CafCoreTypesDoc/CProtocolCollectionDoc.h"

#include "Doc/DocXml/CafCoreTypesXml/CafCoreTypesXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the ProtocolCollection class to/from XML
	namespace ProtocolCollectionXml {

		/// Adds the ProtocolCollectionDoc into the XML.
		void CAFCORETYPESXML_LINKAGE add(
			const SmartPtrCProtocolCollectionDoc protocolCollectionDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ProtocolCollectionDoc from the XML.
		SmartPtrCProtocolCollectionDoc CAFCORETYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
