/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef RequestParameterXml_h_
#define RequestParameterXml_h_


#include "Doc/CafCoreTypesDoc/CRequestParameterDoc.h"

#include "Doc/DocXml/CafCoreTypesXml/CafCoreTypesXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the RequestParameter class to/from XML
	namespace RequestParameterXml {

		/// Adds the RequestParameterDoc into the XML.
		void CAFCORETYPESXML_LINKAGE add(
			const SmartPtrCRequestParameterDoc requestParameterDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the RequestParameterDoc from the XML.
		SmartPtrCRequestParameterDoc CAFCORETYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
