/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef EventManifestXml_h_
#define EventManifestXml_h_


#include "Doc/ResponseDoc/CEventManifestDoc.h"

#include "Doc/DocXml/ResponseXml/ResponseXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the EventManifest class to/from XML
	namespace EventManifestXml {

		/// Adds the EventManifestDoc into the XML.
		void RESPONSEXML_LINKAGE add(
			const SmartPtrCEventManifestDoc eventManifestDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the EventManifestDoc from the XML.
		SmartPtrCEventManifestDoc RESPONSEXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
