/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef EventKeyCollectionXml_h_
#define EventKeyCollectionXml_h_


#include "Doc/ResponseDoc/CEventKeyCollectionDoc.h"

#include "Doc/DocXml/ResponseXml/ResponseXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the EventKeyCollection class to/from XML
	namespace EventKeyCollectionXml {

		/// Adds the EventKeyCollectionDoc into the XML.
		void RESPONSEXML_LINKAGE add(
			const SmartPtrCEventKeyCollectionDoc eventKeyCollectionDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the EventKeyCollectionDoc from the XML.
		SmartPtrCEventKeyCollectionDoc RESPONSEXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
