/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ManifestCollectionXml_h_
#define ManifestCollectionXml_h_


#include "Doc/ResponseDoc/CManifestCollectionDoc.h"

#include "Doc/DocXml/ResponseXml/ResponseXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the ManifestCollection class to/from XML
	namespace ManifestCollectionXml {

		/// Adds the ManifestCollectionDoc into the XML.
		void RESPONSEXML_LINKAGE add(
			const SmartPtrCManifestCollectionDoc manifestCollectionDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ManifestCollectionDoc from the XML.
		SmartPtrCManifestCollectionDoc RESPONSEXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
