/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ResponseHeaderXml_h_
#define ResponseHeaderXml_h_


#include "Doc/ResponseDoc/CResponseHeaderDoc.h"

#include "Doc/DocXml/ResponseXml/ResponseXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the ResponseHeader class to/from XML
	namespace ResponseHeaderXml {

		/// Adds the ResponseHeaderDoc into the XML.
		void RESPONSEXML_LINKAGE add(
			const SmartPtrCResponseHeaderDoc responseHeaderDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ResponseHeaderDoc from the XML.
		SmartPtrCResponseHeaderDoc RESPONSEXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
