/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef GetInventoryJobXml_h_
#define GetInventoryJobXml_h_


#include "Doc/CafInstallRequestDoc/CGetInventoryJobDoc.h"

#include "Doc/DocXml/CafInstallRequestXml/CafInstallRequestXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the GetInventoryJob class to/from XML
	namespace GetInventoryJobXml {

		/// Adds the GetInventoryJobDoc into the XML.
		void CAFINSTALLREQUESTXML_LINKAGE add(
			const SmartPtrCGetInventoryJobDoc getInventoryJobDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the GetInventoryJobDoc from the XML.
		SmartPtrCGetInventoryJobDoc CAFINSTALLREQUESTXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
