/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef InstallProviderJobXml_h_
#define InstallProviderJobXml_h_


#include "Doc/CafInstallRequestDoc/CInstallProviderJobDoc.h"

#include "Doc/DocXml/CafInstallRequestXml/CafInstallRequestXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the InstallProviderJob class to/from XML
	namespace InstallProviderJobXml {

		/// Adds the InstallProviderJobDoc into the XML.
		void CAFINSTALLREQUESTXML_LINKAGE add(
			const SmartPtrCInstallProviderJobDoc installProviderJobDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the InstallProviderJobDoc from the XML.
		SmartPtrCInstallProviderJobDoc CAFINSTALLREQUESTXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
