/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef PackageDefnXml_h_
#define PackageDefnXml_h_


#include "Doc/CafInstallRequestDoc/CPackageDefnDoc.h"

#include "Doc/DocXml/CafInstallRequestXml/CafInstallRequestXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the PackageDefn class to/from XML
	namespace PackageDefnXml {

		/// Adds the PackageDefnDoc into the XML.
		void CAFINSTALLREQUESTXML_LINKAGE add(
			const SmartPtrCPackageDefnDoc packageDefnDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the PackageDefnDoc from the XML.
		SmartPtrCPackageDefnDoc CAFINSTALLREQUESTXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
