/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ProviderInfraXml_Inc_h_
#define ProviderInfraXml_Inc_h_

#include "../CafCoreTypesXml/CafCoreTypesXmlLink.h"
#include "ClassCollectionXml.h"
#include "ProviderRegXml.h"
#include "SchemaSummaryXml.h"
#include "ProviderInfraXmlRoots.h"

#endif /* ProviderInfraXml_Inc_h_ */
