/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef DiagRequestXml_Link_h_
#define DiagRequestXml_Link_h_

#ifndef DIAGREQUESTXML_LINKAGE
    #ifdef WIN32
        #ifdef FRAMEWORK_BUILD
            #define DIAGREQUESTXML_LINKAGE __declspec(dllexport)
        #else
            #define DIAGREQUESTXML_LINKAGE __declspec(dllimport)
        #endif
    #else
        #define DIAGREQUESTXML_LINKAGE
    #endif
#endif


#endif /* DiagRequestXml_Link_h_ */
