/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CProviderCollectInstancesDoc_h_
#define CProviderCollectInstancesDoc_h_

namespace Caf {

/// A simple container for objects of type ProviderCollectInstances
class CProviderCollectInstancesDoc {
public:
	CProviderCollectInstancesDoc() :
		_jobId(CAFCOMMON_GUID_NULL),
		_isInitialized(false) {}
	virtual ~CProviderCollectInstancesDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::string classNamespace,
		const std::string className,
		const std::string classVersion,
		const UUID jobId,
		const std::string outputDir,
		const SmartPtrCParameterCollectionDoc parameterCollection) {
		if (! _isInitialized) {
			_classNamespace = classNamespace;
			_className = className;
			_classVersion = classVersion;
			_jobId = jobId;
			_outputDir = outputDir;
			_parameterCollection = parameterCollection;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the ClassNamespace
	std::string getClassNamespace() const {
		return _classNamespace;
	}

	/// Accessor for the ClassName
	std::string getClassName() const {
		return _className;
	}

	/// Accessor for the ClassVersion
	std::string getClassVersion() const {
		return _classVersion;
	}

	/// Accessor for the JobId
	UUID getJobId() const {
		return _jobId;
	}

	/// Accessor for the OutputDir
	std::string getOutputDir() const {
		return _outputDir;
	}

	/// Accessor for the ParameterCollection
	SmartPtrCParameterCollectionDoc getParameterCollection() const {
		return _parameterCollection;
	}

private:
	std::string _classNamespace;
	std::string _className;
	std::string _classVersion;
	UUID _jobId;
	std::string _outputDir;
	SmartPtrCParameterCollectionDoc _parameterCollection;
	bool _isInitialized;

private:
	CAF_CM_DECLARE_NOCOPY(CProviderCollectInstancesDoc);
};

CAF_DECLARE_SMART_POINTER(CProviderCollectInstancesDoc);

}

#endif
