/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CProviderRequestDoc_h_
#define CProviderRequestDoc_h_

namespace Caf {

/// A simple container for objects of type ProviderRequest
class CProviderRequestDoc {
public:
	CProviderRequestDoc() :
		_clientId(CAFCOMMON_GUID_NULL),
		_requestId(CAFCOMMON_GUID_NULL),
		_isInitialized(false) {}
	virtual ~CProviderRequestDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const UUID clientId,
		const UUID requestId,
		const std::string pmeId,
		const SmartPtrCProviderRequestHeaderDoc requestHeader,
		const SmartPtrCProviderBatchDoc batch,
		const SmartPtrCAttachmentCollectionDoc attachmentCollection) {
		if (! _isInitialized) {
			_clientId = clientId;
			_requestId = requestId;
			_pmeId = pmeId;
			_requestHeader = requestHeader;
			_batch = batch;
			_attachmentCollection = attachmentCollection;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the ClientId
	UUID getClientId() const {
		return _clientId;
	}

	/// Accessor for the RequestId
	UUID getRequestId() const {
		return _requestId;
	}

	/// Accessor for the PmeId
	std::string getPmeId() const {
		return _pmeId;
	}

	/// Accessor for the RequestHeader
	SmartPtrCProviderRequestHeaderDoc getRequestHeader() const {
		return _requestHeader;
	}

	/// Accessor for the Batch
	SmartPtrCProviderBatchDoc getBatch() const {
		return _batch;
	}

	/// Accessor for the AttachmentCollection
	SmartPtrCAttachmentCollectionDoc getAttachmentCollection() const {
		return _attachmentCollection;
	}

private:
	UUID _clientId;
	UUID _requestId;
	std::string _pmeId;
	SmartPtrCProviderRequestHeaderDoc _requestHeader;
	SmartPtrCProviderBatchDoc _batch;
	SmartPtrCAttachmentCollectionDoc _attachmentCollection;
	bool _isInitialized;

private:
	CAF_CM_DECLARE_NOCOPY(CProviderRequestDoc);
};

CAF_DECLARE_SMART_POINTER(CProviderRequestDoc);

}

#endif
