/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CMgmtBatchDoc_h_
#define CMgmtBatchDoc_h_

namespace Caf {

/// A simple container for objects of type MgmtBatch
class CMgmtBatchDoc {
public:
	CMgmtBatchDoc() :
		_isInitialized(false) {}
	virtual ~CMgmtBatchDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const SmartPtrCMgmtCollectSchemaDoc collectSchema,
		const SmartPtrCMgmtCollectInstancesCollectionDoc collectInstancesCollection,
		const SmartPtrCMgmtInvokeOperationCollectionDoc invokeOperationCollection) {
		if (! _isInitialized) {
			_collectSchema = collectSchema;
			_collectInstancesCollection = collectInstancesCollection;
			_invokeOperationCollection = invokeOperationCollection;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the CollectSchema
	SmartPtrCMgmtCollectSchemaDoc getCollectSchema() const {
		return _collectSchema;
	}

	/// Accessor for the CollectInstancesCollection
	SmartPtrCMgmtCollectInstancesCollectionDoc getCollectInstancesCollection() const {
		return _collectInstancesCollection;
	}

	/// Accessor for the InvokeOperationCollection
	SmartPtrCMgmtInvokeOperationCollectionDoc getInvokeOperationCollection() const {
		return _invokeOperationCollection;
	}

private:
	bool _isInitialized;

	SmartPtrCMgmtCollectSchemaDoc _collectSchema;
	SmartPtrCMgmtCollectInstancesCollectionDoc _collectInstancesCollection;
	SmartPtrCMgmtInvokeOperationCollectionDoc _invokeOperationCollection;

private:
	CAF_CM_DECLARE_NOCOPY(CMgmtBatchDoc);
};

CAF_DECLARE_SMART_POINTER(CMgmtBatchDoc);

}

#endif
