/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CMgmtCollectInstancesCollectionDoc_h_
#define CMgmtCollectInstancesCollectionDoc_h_

namespace Caf {

/// A simple container for objects of type MgmtCollectInstancesCollection
class CMgmtCollectInstancesCollectionDoc {
public:
	CMgmtCollectInstancesCollectionDoc() :
		_isInitialized(false) {}
	virtual ~CMgmtCollectInstancesCollectionDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<SmartPtrCMgmtCollectInstancesDoc> collectInstancesCollection) {
		if (! _isInitialized) {
			_collectInstancesCollection = collectInstancesCollection;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the CollectInstances
	std::deque<SmartPtrCMgmtCollectInstancesDoc> getCollectInstancesCollection() const {
		return _collectInstancesCollection;
	}

private:
	bool _isInitialized;

	std::deque<SmartPtrCMgmtCollectInstancesDoc> _collectInstancesCollection;

private:
	CAF_CM_DECLARE_NOCOPY(CMgmtCollectInstancesCollectionDoc);
};

CAF_DECLARE_SMART_POINTER(CMgmtCollectInstancesCollectionDoc);

}

#endif
