#!/bin/sh

scriptsDir=$(dirname $(readlink -f $0))
configDir=$scriptsDir/../config
. $scriptsDir/caf-common
sourceCafenv "$configDir"

processName="CommAmqpListener"
stopProcess "$CAF_BIN_DIR" "$processName"
