/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CMultiPmeMgmtBatchDoc_h_
#define CMultiPmeMgmtBatchDoc_h_

namespace Caf {

/// A simple container for objects of type MultiPmeMgmtBatch
class CMultiPmeMgmtBatchDoc {
public:
	CMultiPmeMgmtBatchDoc() :
		_isInitialized(false) {}
	virtual ~CMultiPmeMgmtBatchDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const SmartPtrCPmeIdCollectionDoc pmeIdCollection,
		const SmartPtrCMgmtBatchDoc batch) {
		if (! _isInitialized) {
			_pmeIdCollection = pmeIdCollection;
			_batch = batch;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the PmeIdCollection
	SmartPtrCPmeIdCollectionDoc getPmeIdCollection() const {
		return _pmeIdCollection;
	}

	/// Accessor for the Batch
	SmartPtrCMgmtBatchDoc getBatch() const {
		return _batch;
	}

private:
	bool _isInitialized;

	SmartPtrCPmeIdCollectionDoc _pmeIdCollection;
	SmartPtrCMgmtBatchDoc _batch;

private:
	CAF_CM_DECLARE_NOCOPY(CMultiPmeMgmtBatchDoc);
};

CAF_DECLARE_SMART_POINTER(CMultiPmeMgmtBatchDoc);

}

#endif
