/*
 *  Author: bwilliams
 *  Created: July 3, 2015
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef PayloadEnvelopeXml_h_
#define PayloadEnvelopeXml_h_

namespace Caf {

	/// Streams the PayloadEnvelope class to/from XML
	namespace PayloadEnvelopeXml {

		/// Adds the PayloadEnvelopeDoc into the XML.
		void PAYLOADENVELOPEXML_LINKAGE add(
			const SmartPtrCPayloadEnvelopeDoc payloadEnvelopeDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the PayloadEnvelopeDoc from the XML.
		SmartPtrCPayloadEnvelopeDoc PAYLOADENVELOPEXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
