/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CAddInCollectionDoc_h_
#define CAddInCollectionDoc_h_

namespace Caf {

/// A simple container for objects of type AddInCollection
class CAddInCollectionDoc {
public:
	CAddInCollectionDoc() :
		_isInitialized(false) {}
	virtual ~CAddInCollectionDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<std::string> addInCollection = std::deque<std::string>()) {
		if (! _isInitialized) {
			_addInCollection = addInCollection;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the AddIn
	std::deque<std::string> getAddInCollection() const {
		return _addInCollection;
	}

private:
	bool _isInitialized;

	std::deque<std::string> _addInCollection;

private:
	CAF_CM_DECLARE_NOCOPY(CAddInCollectionDoc);
};

CAF_DECLARE_SMART_POINTER(CAddInCollectionDoc);

}

#endif
