/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CAddInsDoc_h_
#define CAddInsDoc_h_

namespace Caf {

/// A simple container for objects of type AddIns
class CAddInsDoc {
public:
	CAddInsDoc() :
		_isInitialized(false) {}
	virtual ~CAddInsDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<SmartPtrCAddInCollectionDoc> addInCollection = std::deque<SmartPtrCAddInCollectionDoc>()) {
		if (! _isInitialized) {
			_addInCollection = addInCollection;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the AddInCollection
	std::deque<SmartPtrCAddInCollectionDoc> getAddInCollection() const {
		return _addInCollection;
	}

private:
	bool _isInitialized;

	std::deque<SmartPtrCAddInCollectionDoc> _addInCollection;

private:
	CAF_CM_DECLARE_NOCOPY(CAddInsDoc);
};

CAF_DECLARE_SMART_POINTER(CAddInsDoc);

}

#endif
