/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CInlineAttachmentCollectionDoc_h_
#define CInlineAttachmentCollectionDoc_h_

namespace Caf {

/// A simple container for objects of type InlineAttachmentCollection
class CInlineAttachmentCollectionDoc {
public:
	CInlineAttachmentCollectionDoc() :
		_isInitialized(false) {}
	virtual ~CInlineAttachmentCollectionDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<SmartPtrCInlineAttachmentDoc> attachment = std::deque<SmartPtrCInlineAttachmentDoc>()) {
		if (! _isInitialized) {
			_attachment = attachment;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the InlineAttachment
	std::deque<SmartPtrCInlineAttachmentDoc> getInlineAttachment() const {
		return _attachment;
	}

private:
	bool _isInitialized;

	std::deque<SmartPtrCInlineAttachmentDoc> _attachment;

private:
	CAF_CM_DECLARE_NOCOPY(CInlineAttachmentCollectionDoc);
};

CAF_DECLARE_SMART_POINTER(CInlineAttachmentCollectionDoc);

}

#endif
