/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (C) 2012-2016 VMware, Inc.  All rights reserved. -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ActionClassInstanceCollectionXml_h_
#define ActionClassInstanceCollectionXml_h_


#include "Doc/SchemaTypesDoc/CActionClassInstanceCollectionDoc.h"

#include "Doc/DocXml/SchemaTypesXml/SchemaTypesXmlLink.h"
#include "Xml/XmlUtils/CXmlElement.h"

namespace Caf {

	/// Streams the ActionClassInstanceCollection class to/from XML
	namespace ActionClassInstanceCollectionXml {

		/// Adds the ActionClassInstanceCollectionDoc into the XML.
		void SCHEMATYPESXML_LINKAGE add(
			const SmartPtrCActionClassInstanceCollectionDoc actionClassInstanceCollectionDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the ActionClassInstanceCollectionDoc from the XML.
		SmartPtrCActionClassInstanceCollectionDoc SCHEMATYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
