/*
 *	Copyright (c) 2011 VMware, Inc.  All rights reserved.
 *	-- VMware Confidential
 */

#ifndef _Common_ClassMacroStrings_H
#define _Common_ClassMacroStrings_H

extern COMMONGLOBALS_LINKAGE const char _sPRECOND_ISCONSTRUCTED[];
extern COMMONGLOBALS_LINKAGE const char _sPRECOND_ISINITIALIZED[];
extern COMMONGLOBALS_LINKAGE const char _sPRECOND_ISNOTINITIALIZED[];
extern COMMONGLOBALS_LINKAGE const char _sPRECOND_ISNOTREADONLY[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_STRINGEMPTY[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_STRINGPTRNULL[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_STRINGPTREMPTY[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_PTRARRAYNULL[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_PTRARRAYEMPTY[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_STL[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_STL_EMPTY[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_STL_ITERATOR[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_INTERFACE[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_ZERO[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_ISNOTZERO[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_POSITIVE[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_NEGATIVE[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_NONNEGATIVE[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_NOTNULL[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_NULL[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_BOOL[];
extern COMMONGLOBALS_LINKAGE const char _sVALIDATE_GUID[];
extern COMMONGLOBALS_LINKAGE const char _sASSERT_FAILED[];

#endif
