/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CErrorResponseDoc_h_
#define CErrorResponseDoc_h_

namespace Caf {

/// A simple container for objects of type ErrorResponse
class CErrorResponseDoc {
public:
	CErrorResponseDoc() :
		_clientId(CAFCOMMON_GUID_NULL),
		_requestId(CAFCOMMON_GUID_NULL),
		_isInitialized(false) {}
	virtual ~CErrorResponseDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const UUID clientId,
		const UUID requestId,
		const std::string pmeId,
		const SmartPtrCResponseHeaderDoc responseHeader,
		const std::string errorMessage) {
		if (! _isInitialized) {
			_clientId = clientId;
			_requestId = requestId;
			_pmeId = pmeId;
			_responseHeader = responseHeader;
			_errorMessage = errorMessage;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the ClientId
	UUID getClientId() const {
		return _clientId;
	}

	/// Accessor for the RequestId
	UUID getRequestId() const {
		return _requestId;
	}

	/// Accessor for the PmeId
	std::string getPmeId() const {
		return _pmeId;
	}

	/// Accessor for the Response Header
	SmartPtrCResponseHeaderDoc getResponseHeader() const {
		return _responseHeader;
	}

	/// Accessor for the ErrorMessage
	std::string getErrorMessage() const {
		return _errorMessage;
	}

private:
	UUID _clientId;
	UUID _requestId;
	std::string _pmeId;
	SmartPtrCResponseHeaderDoc _responseHeader;
	std::string _errorMessage;
	bool _isInitialized;

private:
	CAF_CM_DECLARE_NOCOPY(CErrorResponseDoc);
};

CAF_DECLARE_SMART_POINTER(CErrorResponseDoc);

}

#endif
