/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CEventKeyCollectionDoc_h_
#define CEventKeyCollectionDoc_h_

namespace Caf {

/// A simple container for objects of type EventKeyCollection
class CEventKeyCollectionDoc {
public:
	CEventKeyCollectionDoc() :
		_isInitialized(false) {}
	virtual ~CEventKeyCollectionDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<SmartPtrCEventKeyDoc> eventKey) {
		if (! _isInitialized) {
			_eventKey = eventKey;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the EventKey
	std::deque<SmartPtrCEventKeyDoc> getEventKey() const {
		return _eventKey;
	}

private:
	bool _isInitialized;

	std::deque<SmartPtrCEventKeyDoc> _eventKey;

private:
	CAF_CM_DECLARE_NOCOPY(CEventKeyCollectionDoc);
};

CAF_DECLARE_SMART_POINTER(CEventKeyCollectionDoc);

}

#endif
