/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CManifestCollectionDoc_h_
#define CManifestCollectionDoc_h_

namespace Caf {

/// A simple container for objects of type ManifestCollection
class CManifestCollectionDoc {
public:
	CManifestCollectionDoc() :
		_isInitialized(false) {}
	virtual ~CManifestCollectionDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<SmartPtrCManifestDoc> manifest) {
		if (! _isInitialized) {
			_manifest = manifest;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the Manifest
	std::deque<SmartPtrCManifestDoc> getManifest() const {
		return _manifest;
	}

private:
	bool _isInitialized;

	std::deque<SmartPtrCManifestDoc> _manifest;

private:
	CAF_CM_DECLARE_NOCOPY(CManifestCollectionDoc);
};

CAF_DECLARE_SMART_POINTER(CManifestCollectionDoc);

}

#endif
