/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CDiagSetValueCollectionDoc_h_
#define CDiagSetValueCollectionDoc_h_

namespace Caf {

/// A simple container for objects of type DiagSetValueCollection
class CDiagSetValueCollectionDoc {
public:
	CDiagSetValueCollectionDoc() :
		_isInitialized(false) {}
	virtual ~CDiagSetValueCollectionDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const std::deque<SmartPtrCDiagSetValueDoc> setValueCollection) {
		if (! _isInitialized) {
			_setValueCollection = setValueCollection;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the SetValue
	std::deque<SmartPtrCDiagSetValueDoc> getSetValueCollection() const {
		return _setValueCollection;
	}

private:
	bool _isInitialized;

	std::deque<SmartPtrCDiagSetValueDoc> _setValueCollection;

private:
	CAF_CM_DECLARE_NOCOPY(CDiagSetValueCollectionDoc);
};

CAF_DECLARE_SMART_POINTER(CDiagSetValueCollectionDoc);

}

#endif
