/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CMinPackageElemDoc_h_
#define CMinPackageElemDoc_h_

namespace Caf {

/// A simple container for objects of type MinPackageElem
class CMinPackageElemDoc {
public:
	CMinPackageElemDoc() :
		_index(0),
		_isInitialized(false) {}
	virtual ~CMinPackageElemDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const int32 index,
		const std::string packageNamespace,
		const std::string packageName,
		const std::string packageVersion) {
		if (! _isInitialized) {
			_index = index;
			_packageNamespace = packageNamespace;
			_packageName = packageName;
			_packageVersion = packageVersion;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the Index
	int32 getIndex() const {
		return _index;
	}

	/// Accessor for the PackageNamespace
	std::string getPackageNamespace() const {
		return _packageNamespace;
	}

	/// Accessor for the PackageName
	std::string getPackageName() const {
		return _packageName;
	}

	/// Accessor for the PackageVersion
	std::string getPackageVersion() const {
		return _packageVersion;
	}

private:
	int32 _index;
	std::string _packageNamespace;
	std::string _packageName;
	std::string _packageVersion;
	bool _isInitialized;

private:
	CAF_CM_DECLARE_NOCOPY(CMinPackageElemDoc);
};

CAF_DECLARE_SMART_POINTER(CMinPackageElemDoc);

}

#endif
