/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef ResponseXml_Inc_h_
#define ResponseXml_Inc_h_

#include "../CafCoreTypesXml/CafCoreTypesXmlLink.h"
#include "ManifestXml.h"
#include "EventManifestXml.h"
#include "ManifestCollectionXml.h"
#include "EventKeyXml.h"
#include "EventKeyCollectionXml.h"
#include "ProviderResponseXml.h"
#include "ProviderEventResponseXml.h"
#include "ResponseXml.h"
#include "ResponseHeaderXml.h"
#include "ErrorResponseXml.h"
#include "ResponseXmlRoots.h"

#endif /* ResponseXml_Inc_h_ */
