/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppDoc". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef CCdifDoc_h_
#define CCdifDoc_h_

namespace Caf {

/// A simple container for objects of type Cdif
class CCdifDoc {
public:
	CCdifDoc() :
		_isInitialized(false) {}
	virtual ~CCdifDoc() {}

public:
	/// Initializes the object with everything required by this
	/// container. Once initialized, this object cannot
	/// be changed (i.e. it is immutable).
	void initialize(
		const SmartPtrCRequestIdentifierDoc requestIdentifier,
		const SmartPtrCDefinitionObjectCollectionDoc definitionObjectCollection,
		const SmartPtrCSchemaDoc schema) {
		if (! _isInitialized) {
			_requestIdentifier = requestIdentifier;
			_definitionObjectCollection = definitionObjectCollection;
			_schema = schema;

			_isInitialized = true;
		}
	}

public:
	/// Accessor for the RequestIdentifier
	SmartPtrCRequestIdentifierDoc getRequestIdentifier() const {
		return _requestIdentifier;
	}

	/// Accessor for the DefinitionObjectCollection
	SmartPtrCDefinitionObjectCollectionDoc getDefinitionObjectCollection() const {
		return _definitionObjectCollection;
	}

	/// Accessor for the Schema
	SmartPtrCSchemaDoc getSchema() const {
		return _schema;
	}

private:
	bool _isInitialized;

	SmartPtrCRequestIdentifierDoc _requestIdentifier;
	SmartPtrCDefinitionObjectCollectionDoc _definitionObjectCollection;
	SmartPtrCSchemaDoc _schema;

private:
	CAF_CM_DECLARE_NOCOPY(CCdifDoc);
};

CAF_DECLARE_SMART_POINTER(CCdifDoc);

}

#endif
