/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef MgmtTypesXml_Inc_h_
#define MgmtTypesXml_Inc_h_

#include "../CafCoreTypesXml/CafCoreTypesXmlLink.h"
#include "MgmtCollectSchemaXml.h"
#include "MgmtCollectInstancesXml.h"
#include "MgmtInvokeOperationXml.h"
#include "MgmtCollectInstancesCollectionXml.h"
#include "MgmtInvokeOperationCollectionXml.h"
#include "MgmtBatchXml.h"

#endif /* MgmtTypesXml_Inc_h_ */
