/*
 *  Author: bwilliams
 *  Created: April 6, 2012
 *
 *  Copyright (c) 2012 Vmware, Inc.  All rights reserved.
 *  -- VMware Confidential
 *
 *  This code was generated by the script "build/dev/codeGen/genCppXml". Please
 *  speak to Brian W. before modifying it by hand.
 *
 */

#ifndef MgmtCollectSchemaXml_h_
#define MgmtCollectSchemaXml_h_

namespace Caf {

	/// Streams the MgmtCollectSchema class to/from XML
	namespace MgmtCollectSchemaXml {

		/// Adds the MgmtCollectSchemaDoc into the XML.
		void MGMTTYPESXML_LINKAGE add(
			const SmartPtrCMgmtCollectSchemaDoc mgmtCollectSchemaDoc,
			const SmartPtrCXmlElement thisXml);

		/// Parses the MgmtCollectSchemaDoc from the XML.
		SmartPtrCMgmtCollectSchemaDoc MGMTTYPESXML_LINKAGE parse(
			const SmartPtrCXmlElement thisXml);
	}
}

#endif
